spring:
  application:
    name: notification-service
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.rideshare: DEBUG
